---
- name: Prepare the Rancher Master Server
  hosts: all
  become: True
 
  vars:
    - myrole: master
 
  tasks: 
    - hostname: 
        name: "{{ myrole }}"
    - import_tasks: includes/playbook_include_basics.yml
    - import_tasks: includes/playbook_include_docker.yml
    - import_tasks: includes/playbook_include_ranchermaster.yml         