############ Docker-ce installation

    - name: Add repo key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Setup docker repo
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
        state: present

    - name: Install docker-ce from new repo
      apt:
        name: docker-ce=17.03.3~ce-0~ubuntu-xenial        

    - name: Run docker service
      systemd: 
        name: docker
        state: started
        enabled: yes
